### ISSUE TITLE
Document example readings for first pass Network Telemetry

### ISSUE THREAD

**Issue by KylerBurke** [vapor-ware/synse-openconfig-plugin#10]
The identified metrics for our initial OpenConfig consumption are:
- Ingress
- Egress
- Ingress Throughput
- Egress Throughput
- Error (rate/number)

Once these initial values have been isolated from the plethora of openconfig data, example readings should be provided for the purpose of tangental emulation. Data of value for crafting a realistic emulator includes data type, estimates of range, and variability.

**Comment by edaniszewski** [comment]
estimates of range and variability are effectively boundless because it is valid for there to be 0kb/s, 10Mb/s, 100Mb/s, etc. Variability may also change depending on what would be generating network traffic, so I don't know that there are data around what are realistic values for that. We probably want to define these ranges for the emulator for sanity, but empirically, I don't think there is much limiting that.
