### ISSUE TITLE
Verify plugin configuration provides correct context/metadata in readings

### ISSUE THREAD

**Issue by KylerBurke** [vapor-ware/synse-openconfig-plugin#11]
This is a post deployment step, to ensure the readings provided by the plugin provide enough context to generate proper Prometheus metrics. Here is a discussion in Edge-Monitor that outlines the unique metadata needed to generate useful readings: https://github.com/vapor-ware/edge-monitor/issues/84

**Comment by edaniszewski** [comment]
The context fields defined in the linked issue exist and are generated via the plugin, with two exceptions:

- the `site_id` is generated in the device config, so it is up to the configurer/deployer to ensure that is set
- not all metrics will have a directionality, since not all networking metrics are tied to ingress/egress

Example from the demo deployment:

```
  {
    "device": "7d136007-df3c-50a1-8baf-dcd74f54619c",
    "timestamp": "2021-01-19T20:17:43Z",
    "type": "string",
    "device_type": "interface",
    "unit": null,
    "value": "",
    "context": {
      "site": "ke2-atl",
      "system_id": "efr2.ke2.atl",
      "metric": "parent_ae_name",
      "metric_type": "network",
      "interface_name": "xe-0\/0\/46"
    }
  }
```

Leaving this open, as this issue is a post-deploy validation step. Just noting that it _should_ not require a lot of effort.
